TTGO_WIDTH = 25.09
TTGO_HEIGHT = 51.49
TTGO_HEIGHT_WITH_USB = 53
TTGO_DEPTH_WITH_DISPLAY = 3
TTGO_DEPTH_WITH_RESET = 3
TTGO_DEPTH_WITH_USB = 4.3
USB_WIDTH = 9
USB_HEIGHT = 7.3
DISPLAY_HEIGHT = 26
DISPLAY_WIDTH = 16.5
DISPLAY_OFFSET = 6.7
BUTTON_WIDTH = 3.3
BUTTON_HEIGHT = 4.1
BUTTON_CENTER_OFFSET_X = 4.5
BUTTON_CENTER_OFFSET_Y = 3.2
RESET_CENTER_OFFSET_Y = 11
RESET_HEIGHT = 4.5
VOLNY_KONEC = 5.4

import cadquery as cq

from common import render

wp = cq.Workplane("XY")


render(wp, 'proticakaci_tyce.stl')
